issue-58: Add closeMenu function and RootCloseWrapper
attivio/suit pull request #59
Opened 2018-10-29 19:29 UTC by brandon-bogan

FacetSearchBar will now close its suggestion menu when a user clicks somewhere else

2019-07-23 23:10 UTC, luigivaldez requested changes
See my comment about your comment.... Otherwise, this looks good.

2019-07-23 23:10 UTC, luigivaldez commented on src/components/FacetSearchBar.js
> +    this.doConfiguredSearch(`${this.state.facetValue}*`, this.props.maxValues * 2, callback, this.context.searcher); // `
What's up with this comment? Can you remove it?

2019-10-09 17:33 UTC, klk1010 commented on src/components/FacetSearchBar.js
> +    this.doConfiguredSearch(`${this.state.facetValue}*`, this.props.maxValues * 2, callback, this.context.searcher); // `
```suggestion
    this.doConfiguredSearch(`${this.state.facetValue}*`, this.props.maxValues * 2, callback, this.context.searcher);
```

2019-10-15 17:09 UTC, brandon-bogan commented on src/components/FacetSearchBar.js
> +    this.doConfiguredSearch(`${this.state.facetValue}*`, this.props.maxValues * 2, callback, this.context.searcher); // `
Fixed in latest commit

2019-11-25 16:17 UTC, luigivaldez approved these changes

2019-11-25 16:36 UTC, merged